apiVersion: v1
kind: Service
metadata:
  name: pingora-headless
  namespace: ingress
  labels:
    app: pingora
spec:
  clusterIP: None
  selector:
    app: pingora
  ports:
    - name: gossip-udp
      port: 11204
      targetPort: 11204
      protocol: UDP
